"""add relationship between orders and product

Revision ID: 21f1948c82b6
Revises: 305560885e12
Create Date: 2022-05-20 00:37:47.374960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f1948c82b6'
down_revision = '305560885e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'order_id')
    # ### end Alembic commands ###
