"""empty message

Revision ID: 305560885e12
Revises: c7507729405b
Create Date: 2022-05-19 15:21:15.351329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305560885e12'
down_revision = 'c7507729405b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('payment', sa.String(length=100), nullable=True))
    op.drop_column('supplier', 'payment_mode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('payment_mode', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('supplier', 'payment')
    # ### end Alembic commands ###
