"""Update Migaration

Revision ID: 69595248cde8
Revises: e9126b75dfd1
Create Date: 2022-05-18 00:39:33.917498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69595248cde8'
down_revision = 'e9126b75dfd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('Supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'supplier', ['Supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'Supplier_id')
    # ### end Alembic commands ###
