"""Update Migaration

Revision ID: c7507729405b
Revises: 69595248cde8
Create Date: 2022-05-18 12:28:22.441081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7507729405b'
down_revision = '69595248cde8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'customer', ['customer_id'], ['id'])
    op.drop_column('orders', 'name')
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.drop_constraint('products_Supplier_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_Category_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'supplier', ['supplier_id'], ['id'])
    op.create_foreign_key(None, 'products', 'category', ['category_id'], ['id'])
    op.drop_column('products', 'Supplier_id')
    op.drop_column('products', 'Category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('Category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('Supplier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_Category_id_fkey', 'products', 'category', ['Category_id'], ['id'])
    op.create_foreign_key('products_Supplier_id_fkey', 'products', 'supplier', ['Supplier_id'], ['id'])
    op.drop_column('products', 'supplier_id')
    op.drop_column('products', 'category_id')
    op.add_column('orders', sa.Column('name', sa.VARCHAR(length=90), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'customer_id')
    # ### end Alembic commands ###
